# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  repository: 'lexslimx/alexkesite'

pool:
      vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: $(repository)
        dockerfile: 'Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: 'dockerHub'
        repository: $(repository)
        command: push
        tags: |
          $(tag)
          
- stage: DeployK8
  displayName: Deploy To K8s
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'EnterpriseAccSpAexKe'
        azureResourceGroup: 'alexke-rg'
        kubernetesCluster: 'alexkecluster'
        useClusterAdmin: true
        command: 'apply'
        useConfigurationFile: true
        configuration: 'deploy/alexke-namespace.yml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'EnterpriseAccSpAlexKe'
        azureResourceGroup: 'alexke-rg'
        kubernetesCluster: 'alexkecluster'
        useClusterAdmin: true
        namespace: 'alexke'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'deploy/alexke-deployment.yml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'EnterpriseAccSpAlexKe'
        azureResourceGroup: 'alexke-rg'
        kubernetesCluster: 'alexkecluster'
        useClusterAdmin: true
        namespace: 'alexke'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'deploy/alexke-service.yml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
- stage: DeployIngress
  displayName: Deploy Ingress
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'EnterpriseAccSpAlexKe'
        azureResourceGroup: 'alexke-rg'
        kubernetesCluster: 'alexkecluster'
        useClusterAdmin: true
        namespace: 'nginx-ingress'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'deploy/nginx-namespace.yml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'

    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'EnterpriseAccSpAlexKe'
        azureResourceGroup: 'alexke-rg'
        kubernetesCluster: 'alexkecluster'
        useClusterAdmin: true
        command: 'apply'
        useConfigurationFile: true
        configuration: 'deploy/nginx-ingress.yml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'

      
