apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexke
  labels:
    app: alexke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alexke
  template:
    metadata:
      labels:
        app: alexke
    spec:
      containers:
      - name: alexke
        image: lexslimx/alexkesite:1647
        ports:
        - containerPort: 80
